server:
  port: 8080

jwt:
  secret: "294A404E635266556A586E327235753878214125442A472D4B6150645367566B"

feign:
  client:
    product-service:
      url: http://localhost:9090
    shopping-cart-service:
      url: http://localhost:9095
    report-service:
      url: http://localhost:9096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactions
    username: root
    password: Sebitas2515
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    feign.Logger: DEBUG
    com.MicroService.MicroServiceTransaction.infrastructure.input.rest.feign: DEBUG
